---

- name: restart teleport
  shell: "sleep 5 && service teleport restart"
  async: 1
  poll: 0
  register: teleport_restart

- name: check restart status
  ansible.builtin.async_status:
    jid: "{{ teleport_restart.ansible_job_id }}"
  ignore_errors: true
  register: job_result
  until: job_result.finished
  retries: 10
  delay: 5
