# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true
    d.remains_running = true
  end

  config.vm.synced_folder "../", "/code"
  config.vm.define "docker"

  config.vm.provision "ansible_local" do |ansible|
    ansible.install = true
    ansible.install_mode = "pip"
    ansible.playbook = "/code/tests/test.yml"
    ansible.verbose = "vvv"
    ansible.become = true
    ansible.compatibility_mode = "2.0"
    # ansible.galaxy_role_file = "../requirements.yml"
    ansible.groups = {
      "test" => ["docker", "localhost", "all"],
      }
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
  end
end
