# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true
    d.remains_running = true
  end

  config.vm.synced_folder "../../", "/code"
  config.vm.define "docker"

  config.vm.provision "ansible_local" do |ansible|
    ansible.install = true
    ansible.install_mode = "pip"
    ansible.playbook = "/code/tests/test.yml"
    ansible.verbose = "vvv"
    ansible.become = true
    ansible.compatibility_mode = "2.0"
    ansible.groups = {
      "test" => ["docker"],
      }
  end

end
